layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: ExplodingPineapple
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: ExplodingPineap
  # unsplash: your_username
  # vk: your_username
  website: https://explodingpineapple.net
  matrix: +explodingpineapple:matrix.org
  discord: euf9d5Y
  youtube: ExplodingPineapple

links:
  - name: Discord Community
    web_url: https://discord.gg/euf9d5Y
    image_url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOMAAADeCAMAAAD4tEcNAAAAgVBMVEX///8AAACJiYmlpaVxcXH29vb5+fnz8/P8/Pzj4+OioqKMjIzBwcE8PDzb29vm5ubLy8uYmJitra3S0tIjIyN7e3uSkpIvLy9hYWEaGhqbm5uzs7NcXFxWVlZGRkbQ0NA2NjYqKipOTk5qamohISF3d3cVFRULCwu8vLxCQkKCgoKycdtgAAAHgUlEQVR4nO2daXuqPBCGXVBcAcGtbi3SWuv//4GvCypmmQTJ9nLm+XSu07DckoSZzGRoNFAoFAqFQqFQKBQKhUKh2OoGx7htU/Ex6OoEDFd/TRe0W4WaCIONbbaCloEGwu6PbSxCs55qxMQ2Eq2D4kd5tA3E1Egl4sg2DUeROkQHO2ouZd21Y5sEkKp3ZWYbBNCPGkR3e+pFanrrzjYGqI0KxMA2hUB9BYwt2xACTRQwTm1DCDSujhjaZhCqU5nRVRPnqc/KjAPbCEKtKzPObSMItarM6Pq02mwO/wHGFjIiIzI6I2RERmR0R8iIjMjojpARGZHRHSEjMiKjO0JGZFTDOF16Y+jv6U+WVruCTcbDcpX4l1P4QKP0mknUSQbZx7vXscaYzvMgth9voXbT1iMkE0wWb13KEuMwD+5213uZm3yEgvvz3/IXs8H4dcwPTV5T7Babn9NpOF8NBqvWzNsX++bfM/Y0AkevG4zje4LX+t7z/paTOAoY2Zh+MBpk91bDR4OoJKVpxsP9GbZvnW4ZJ6L0xE40uY3Y7NFljweHGe/5B9fA7L4tnzsTtdJmMSl15SrjLu9u6/O/N2u/5IWC4fnRe/ejQvmsIJOM7fxeF81x/F4ewqdXSEVpO8iYXJv3suZPhfSuXnzIT3R+kTjHmF1bR81h2T5KapTOyl3aHON1LE7mKpK8o+w2sCEb0Abj9TF+Vk8Huim6nWjmFqOOrQiSOV6mGPcKiBiSyg42xagweb0oqfRgQ4xTBTxMfbnD2FaAw9TaHUZV8ymlnjOMngIajk6uMCbi07wriWx2I4zaZpyLxGs8RhhVZK1zJc4RNsKoa1PpVWKj1QSjgsR8SMKVPROM2l6ONwlfkSYYqzqMAgl37Rlg3CngACXqrAYYBwowQMX2GVXs6QIl8iL1M34ooBBI4HzoZ6x+BaGGthk1ecdFfdpm1FogJJdlRnghJxhup2NvDfwO0Wk/3c0ExQzAKK1+RmhDV/h4s8WcFkmaN/gAuzxsl2tnBFzH4s7JLbPFpNAC2hkGO5HaGfkHvs4US0aL16gN0CPgFQ/djPzhSJqZtDlEPh2gS4DmnG7GOfc4aiGGmnjICCPgo4EbTXUzcidEunuRLhgdeuPHE8BN0boZuUsA9F2R/smEasGfdkCTVTMj31hl2F9EZ6XHGOClWWTkTzmMaAzhS9OW9jf/LiArQDMjv3cxapgR/TqlW/DtIeguNDPyt+YzqpgRz5HONDrw7wJa1NHMyJ8J6RmlSYTRl1SDP/5dQEE6zYz8WA59U2ShG3oJg/+yBVdZNTMCx1EJjEeiAX3b0KoJkF2mlxFakqNSiKgW5JBl2+25gEKTehnBmBzxbqCdJ9KiBUMKQGaAXkawUsZrX2TFfV6NcthPBixWvYw81/emsJCFy55Oiu4XOVwJAW6yXkbBfT0MujHvHdPx8hYbUUABKDipl1EYP+6OhrNTG5ov/XVrdorFIRPgBamXUWvg8VXAcodeRs0Rq6IA76o2jF1bjLSfoCpRhz6zJUaGnxBVLy51Vq9F9xBLjKyclYGCcm9r1mRmiZHptw+bWbXpdrRgumyWGNmrOWeLxHs/7nrZpMO0GFI7jJz348Uk2b5VcrrXPhvyKfOswFK5XkaO497/vvxxWPZh9q+X4vgyQI17zT7yiXPQzUv4G8iPzM765iFy4lfQQrnuNWReqlyY/+5fq0BiN0TYzuMCvDcPuGdHe9yKm7mSPHrXdhUBQdZwdLpXsWW8FW+CtyXpj5Xzkx77hbDONJscE//FCuqEn/HpuTa8aHN/CMEmOgP5OdCCR0IsePxOv3bbbLnZjxffxf8/TID9IV4Tlol8uQV/ZomEB+fiI/aFSbpmcq15IeAStZR5Q1Fis6ehfQEL9pSfyjN+MU8QyZzB2H6rHYOy1LdpGMN6JPf1HoN7PBdr4k1YspIyEWfuxqnkgWb3XHvHwrAq/emWQk/w13TExxHGs1IvDq6gb3xm4Do/+0lcskiJpVoWv+Plt7gVqelSZgsZJfu1ZfQLGZERGd0RMiIjMrojZERGZHRHyIiMyOiOkBEZkdEdISMy3uT+txGrM1r6xmUq37Q6o3SYVK128t9Irc5o65uzvvSPq6AKw9u10asplv6GuAJGxu4wE9pIF5lVwCioJKFNvfM4karIrqJiyHsV7ivrEnL1ZQaKCkZLX4G+3npXIiKppPKLXOqBai1uFxfX8FbCKFtgWrHy1CZhdoiaCj4yFULV676bS5T+oKhKEWPnrX49Nr4KSj+rqsQkKLekR498H9gvUFZtSlQATYeeCTuac3Tv6r+VV1JJhZvXu3f+qdi05ZoWLg5Y6Goro41KZHipUDExlm+hK6/+lsTDmWdI2UsuJfctbaDCnTGFnLFSJ8ZGh+0d1Iqx0WMar/ViZNfRqRsja1WidowMu65+jLTJU0NGyuSpIyNpDdSSseF/15+x0dvXn/FlAaS2jIW4aH0Zn2sDNWZ8rG3XmfG+3anWjI3wUH/GRmdcf8ars1V7xsbsH2BszGfiNv97GayOhkKhUCgUCoVCoVAoFMp1/Qf5rYd5yX7CsAAAAABJRU5ErkJggg==

  - name: Matrix/Riot Community
    web_url: https://matrix.to/#/+explodingpineapple:matrix.org
    image_url: https://t2bot.io/assets/img/mx-riot.png
#
#  - name: Sass
#    web_url: https://github.com/topics/sass
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

topics:
  - name: Gaming
  
  - name: Technology
